### ISSUE TITLE
Problem executing benchmark/eliashberg/tprf_implementation.py in 3.0.0 version

### ISSUE THREAD

**Issue by ParthaSarathiRana** [TRIQS/tprf#22]
While executing the Eliashberg code in the benchmark folder of the package, I am getting the following error :

[eliashberg_py.txt](https://github.com/TRIQS/tprf/files/7355364/eliashberg_py.txt)

  Two-Particle Response Function tool-box 

beta  = 5.0
nk    = 4
nw    = 300
norb  = 1

Approx. Memory Utilization: 0.00 GB

--> fourier_wk_to_wr
--> fourier_wr_to_tr
--> chi0_tr_from_grt_PH (bubble in tau & r)
--> chi_wr_from_chi_tr
--> chi_wk_from_chi_wr (r->k)
Traceback (most recent call last):
  File "/home/partha/tprf.src/benchmark/eliashberg/tprf_implementation.py", line 123, in <module>
    next_delta = eliashberg_product(gamma, g0_wk, init_delta) 
RuntimeError: .. Error occurred at Fri Oct 15 23:59:18 2021

.. Error .. calling C++ overload 
.. eliashberg_product(triqs_tprf::chi_wk_vt Gamma_pp, triqs_tprf::gk_iw_vt g_wk, triqs_tprf::gk_iw_vt delta_wk) -> triqs_tprf::gk_iw_t 
.. in implementation of function lattice.eliashberg_product
.. C++ error was : 
.. Triqs runtime error at /home/partha/tprf.src/c++/triqs_tprf/lattice/eliashberg.cpp : 58

The size of the Matsubara frequency mesh of Gamma (399) must be atleast TWICE the size of the mesh of Delta (300).
.. Error occurred on node 0

**Comment by Stefan-Dienst** [comment]
Hi,

thank you very much for pointing this out.
This script was first used to benchmark against another eliashberg implementation but has long been deprecated, so I think it's best to just remove it, see attached PR.

If you want to see other examples of the eliashberg implementation checkout the following links: 

- https://github.com/TRIQS/tprf/tree/eliashberg_3.0.x/test/python/eliashberg
- https://github.com/TRIQS/tprf/blob/eliashberg_3.0.x/doc/user_guide/Solving%20the%20linearized%20Eliashberg%20equation%20in%20the%20random%20phase%20approximation%20limit.ipynb
-  https://github.com/TRIQS/tprf/blob/eliashberg_3.0.x/doc/user_guide/Linearized%20Eliashberg%20equation%20on%20the%20attractive%20Hubbard%20model.ipynb.

Cheers
Stefan

**Comment by ParthaSarathiRana** [comment]
Thanks
